const CORE_AUTH = 'core_auth';

export const LOGIN = `${CORE_AUTH}/LOGIN`;
export const LOGIN_REQUEST = `${CORE_AUTH}/LOGIN_REQUEST`;
export const LOGIN_SUBMIT = `${CORE_AUTH}/LOGIN_SUBMIT`;
export const LOGIN_SUCCESS = `${CORE_AUTH}/LOGIN_SUCCESS`;
export const LOGIN_ERROR = `${CORE_AUTH}/LOGIN_ERROR`;

export const LOGOUT = `${CORE_AUTH}/LOGOUT`;
export const LOGOUT_REQUEST = `${CORE_AUTH}/LOGOUT_REQUEST`;
export const LOGOUT_SUBMIT = `${CORE_AUTH}/LOGOUT_SUBMIT`;
export const LOGOUT_SUCCESS = `${CORE_AUTH}/LOGOUT_SUCCESS`;
export const LOGOUT_ERROR = `${CORE_AUTH}/LOGOUT_ERROR`;